// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/list-modules.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/course.ts
var mcpCourseModules = [
  {
    id: 1,
    title: "How the Web Works",
    subtitle: "Foundations of the internet, browsers, and the client-server model.",
    sections: [
      {
        title: "Client and server",
        content: "A browser (client) requests a page from a server over HTTP. The server responds with HTML, CSS, and JavaScript that the browser renders."
      }
    ]
  },
  {
    id: 2,
    title: "HTML: Structure",
    subtitle: "Semantic markup for building learning content.",
    sections: [
      { title: "Elements and tags", content: "HTML is made of nested elements that describe content structure." }
    ]
  },
  {
    id: 3,
    title: "The DOM Tree",
    subtitle: "How the browser turns HTML into a live tree JavaScript can manipulate.",
    sections: [{ title: "Nodes", content: "Every element is a node in the DOM tree." }]
  },
  {
    id: 4,
    title: "CSS: Styling",
    subtitle: "Colors, layout, and responsive design.",
    sections: [{ title: "Selectors", content: "Selectors target elements to apply styles." }]
  },
  {
    id: 5,
    title: "JavaScript: Behavior",
    subtitle: "Adding interactivity to learning experiences.",
    sections: [{ title: "Variables and functions", content: "The building blocks of JS logic." }]
  },
  {
    id: 6,
    title: "Building Interactivity",
    subtitle: "Events, state, and dynamic content.",
    sections: [{ title: "Event listeners", content: "Respond to clicks, input, and other user actions." }]
  },
  {
    id: 7,
    title: "Live Code Lab",
    subtitle: "Write and run real code in the browser.",
    sections: [{ title: "Practice", content: "Use the in-browser editor to try HTML/CSS/JS." }]
  }
];
var TOTAL_MODULES = mcpCourseModules.length;

// src/lib/mcp/tools/list-modules.ts
var list_modules_default = defineTool({
  name: "list_modules",
  title: "List course modules",
  description: "Return the outline of every module in the course (id, title, subtitle).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const outline = mcpCourseModules.map((m) => ({ id: m.id, title: m.title, subtitle: m.subtitle }));
    return {
      content: [{ type: "text", text: JSON.stringify(outline, null, 2) }],
      structuredContent: { modules: outline }
    };
  }
});

// src/lib/mcp/tools/get-module.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var get_module_default = defineTool2({
  name: "get_module",
  title: "Get a module",
  description: "Return the full content of a single course module by id.",
  inputSchema: { module_id: z.number().int().describe("Module id (1-7).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ module_id }) => {
    const mod = mcpCourseModules.find((m) => m.id === module_id);
    if (!mod) {
      return { content: [{ type: "text", text: `No module with id ${module_id}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(mod, null, 2) }],
      structuredContent: { module: mod }
    };
  }
});

// src/lib/mcp/tools/get-my-progress.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/supabase-client.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.2";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-progress.ts
var get_my_progress_default = defineTool3({
  name: "get_my_progress",
  title: "Get my course progress",
  description: "Return the signed-in user's completed modules and overall progress.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("course_progress").select("module_id, completed, quiz_score, quiz_total, completed_at").eq("user_id", ctx.getUserId()).order("module_id");
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = data ?? [];
    const completed = rows.filter((r) => r.completed).map((r) => r.module_id);
    const summary = {
      user_id: ctx.getUserId(),
      total_modules: TOTAL_MODULES,
      completed_count: completed.length,
      completed_modules: completed,
      all_completed: completed.length === TOTAL_MODULES,
      progress: rows
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/mark-module-complete.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var mark_module_complete_default = defineTool4({
  name: "mark_module_complete",
  title: "Mark a module complete",
  description: "Mark one module as completed for the signed-in user. Optionally record their quiz score.",
  inputSchema: {
    module_id: z2.number().int().describe("Module id to mark complete."),
    quiz_score: z2.number().int().optional().describe("Number of quiz answers correct."),
    quiz_total: z2.number().int().optional().describe("Total quiz questions.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  needsApproval: true,
  handler: async ({ module_id, quiz_score, quiz_total }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!mcpCourseModules.some((m) => m.id === module_id)) {
      return { content: [{ type: "text", text: `Unknown module id ${module_id}` }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("course_progress").upsert(
      {
        user_id: ctx.getUserId(),
        module_id,
        completed: true,
        quiz_score: quiz_score ?? null,
        quiz_total: quiz_total ?? null,
        completed_at: (/* @__PURE__ */ new Date()).toISOString()
      },
      { onConflict: "user_id,module_id" }
    ).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Marked module ${module_id} complete.` }],
      structuredContent: { row: data }
    };
  }
});

// src/lib/mcp/tools/get-my-certificate.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_my_certificate_default = defineTool5({
  name: "get_my_certificate",
  title: "Get my completion certificate",
  description: "Return the signed-in user's certificate metadata (name, status, issued date). Only issued when every module is complete.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const [{ data: progress, error: pErr }, { data: profile, error: prErr }] = await Promise.all([
      sb.from("course_progress").select("module_id, completed, completed_at").eq("user_id", ctx.getUserId()),
      sb.from("profiles").select("display_name").eq("id", ctx.getUserId()).maybeSingle()
    ]);
    if (pErr) return { content: [{ type: "text", text: pErr.message }], isError: true };
    if (prErr) return { content: [{ type: "text", text: prErr.message }], isError: true };
    const completedRows = (progress ?? []).filter((r) => r.completed);
    const allDone = completedRows.length === TOTAL_MODULES;
    if (!allDone) {
      const out = {
        status: "in_progress",
        completed_count: completedRows.length,
        total_modules: TOTAL_MODULES,
        message: `Certificate is issued once all ${TOTAL_MODULES} modules are complete.`
      };
      return { content: [{ type: "text", text: JSON.stringify(out, null, 2) }], structuredContent: out };
    }
    const issuedAt = completedRows.map((r) => r.completed_at).filter((v) => !!v).sort().at(-1);
    const cert = {
      status: "issued",
      recipient: profile?.display_name ?? ctx.getUserEmail() ?? "Learner",
      course: "Coding Basics for Instructional Designers",
      issued_at: issuedAt
    };
    return { content: [{ type: "text", text: JSON.stringify(cert, null, 2) }], structuredContent: cert };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rwnwbgobscmtramesvja";
var mcp_default = defineMcp({
  name: "coding-basics-mcp",
  title: "Coding Basics for Instructional Designers",
  version: "0.1.0",
  instructions: "Tools for the 'Coding Basics for Instructional Designers' course. Use list_modules and get_module to read course content (public). Use get_my_progress, mark_module_complete, and get_my_certificate to read or update the signed-in user's own progress.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_modules_default, get_module_default, get_my_progress_default, mark_module_complete_default, get_my_certificate_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
